### ISSUE TITLE
Application does not detect networked printer

### ISSUE THREAD

**Issue by jayjayseal** [computerlyrik/dymoprint#116]
Hi,

I have an issue with the application. If i try to print via USB, this works. But i want to use this using a RPI on a network. 
I can print to the printer using `printf "lol" | lp -o landscape` and this works by printing from a remote laptop to CUPS (Dymo 550) connected on a RPI (USB).

But the application (CLI or GUI) cannot find this printer and error's out with the following error.
`$ dymoprint -qr qrencoded "qr_txt"
No Dymo devices found (expected vendor 0x922)
- Vendor ID: 0x1d6b  Product ID: 0x3
- Vendor ID: 0x46d   Product ID: 0xc52b
- Vendor ID: 0x8087  Product ID: 0x26
- Vendor ID: 0x5986  Product ID: 0x211c
- Vendor ID: 0x1d6b  Product ID: 0x2
Unable to open device.
Traceback (most recent call last):
  File "/home/user/.local/bin/dymoprint", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/pipx/venvs/dymoprint/lib/python3.10/site-packages/dymoprint/command_line.py", line 265, in main
    print_label(label_bitmap, margin_px=args.m, tape_size_mm=args.t)
  File "/home/user/.local/pipx/venvs/dymoprint/lib/python3.10/site-packages/dymoprint/dymo_print_engines.py", line 324, in print_label
    detected_device = detect_device()
  File "/home/user/.local/pipx/venvs/dymoprint/lib/python3.10/site-packages/dymoprint/detect.py", line 60, in detect_device
    die("Unable to open device.")
  File "/home/user/.local/pipx/venvs/dymoprint/lib/python3.10/site-packages/dymoprint/utils.py", line 19, in die
    raise RuntimeError(message)
RuntimeError: Unable to open device.
`

**Comment by maresb** [comment]
Ya, currently only printing via USB is supported. However thanks to the recent work of @tomers I think we're getting close to being able to work with networked printers.

> If i try to print via USB, this works.

Does it work for you with `dymoprint`, `lp`, or both? I'm asking because we don't have confirmation that the 550 is compatible. See #44.

**Comment by jayjayseal** [comment]
The Dymo SDK is a mess. But you can get it working with this SDK. Will post details later.

**Comment by jayjayseal** [comment]
OK, here i go. (I have the lablelwriter 500 (usb only)

The reason behind me telling the SDK is a mess is the following:

- The SDK (according to Dymo support) is here: https://github.com/dymosoftware/Drivers
- The LW4xx Linux folder contains the ppd files for the Lablewriter 500 (someone already made a post about this here https://github.com/dymosoftware/Drivers/issues/2
- The installer does not compile correctly. For some users they have an error during compiling.
- The installer "forgets" to do a simple file copy for the raster/filter file.Copy the file (/LW**4**xx Linux/Linux/src/lw/**raster2dymolw_v2**) from the ZIP file to **/usr/lib/cups/filter/**

It will work for printing then.

**Comment by jayjayseal** [comment]
> Does it work for you with `dymoprint`, `lp`, or both? I'm asking because we don't have confirmation that the 550 is compatible. See #44.

If i use `lp` it works for printing, if i print a test page it also fit's it nicely on 1 label. `dymoprint` or `dymoprint_gui` gives the same error not being able to find the printer.

**Comment by maresb** [comment]
Dymoprint without modification won't recognize the 550 since it's not registered in our list of [supported products](https://github.com/computerlyrik/dymoprint/blob/52fb23a6ef6b78bd4f0f737d38708ec5059301bd/src/dymoprint/lib/constants.py#L40).

You can do a [development install](https://github.com/computerlyrik/dymoprint?tab=readme-ov-file#development-and-code-style) and add it yourself. To get the device id which is the key in the dict, just run `lsusb` and you should see a line like:

```
Bus 001 Device 012: ID 0922:1001 Dymo-CoStar Corp. LabelManager PnP
```

Here `0922` is the vendor ID of Dymo, and `1001` is the device id for the LabelManager PnP.

**Comment by jayjayseal** [comment]
`Bus 001 Device 006: ID 0922:0028 Dymo-CoStar Corp. DYMO LabelWriter 550`

For anyone referring in the future

**Comment by tomers** [comment]
@jayjayseal, I recently got A DYMO LavelWriter 550 printer, and hopefully I will be able to add support for that model in the near future.

**Comment by melroy89** [comment]
> @jayjayseal, I recently got A DYMO LavelWriter 550 printer, and hopefully I will be able to add support for that model in the near future.

I'm actually planning to buy a LabelPrinter 550. I hope there is support already. 

In the meanwhile there is an official driver from Dymo themselves: https://github.com/dymosoftware/Drivers
