### ISSUE TITLE
Font-Size

### ISSUE THREAD

**Issue by EmJotGeh** [computerlyrik/dymoprint#46]
It would be nice if you could change the font size.

**Comment by maresb** [comment]
Indeed. Currently, font size is currently dynamic based on the [number of lines](https://github.com/computerlyrik/dymoprint/blob/4f95fcada21c21780514164c682003d26c80a308/src/dymoprint/command_line.py#L184-L185).

In case you're motivated to implement something further, you're welcome to submit a PR! :slightly_smiling_face:

**Comment by maresb** [comment]
Hey @EmJotGeh, do you still have your label printer? I just got a PR which implements this feature in #54. If possible, would you be willing to test it? (My printer is currently broken.)

You can install the testing version with
```bash
pip install git+https://github.com/MooVx/dymoprint@master
```

and then you run `dymoprint_gui`.

**Comment by EmJotGeh** [comment]
Hey @maresb, this sounds pretty nice! I will try it as soon as possible! Thank you very much :-)

**Comment by EmJotGeh** [comment]
Ok, the gui is working well and looks nice - but i get a permission issue:

```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.11/site-packages/dymoprint/gui.py", line 159, in print_label
    self.print_server.print_label(
  File "/home/user/.local/lib/python3.11/site-packages/dymoprint/dymo_print_engines.py", line 274, in print_label
    devout = open(dev, "rb+")
             ^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Keine Berechtigung: '/dev/hidraw1'
Abgebrochen (Speicherabzug geschrieben)
```

and when i try to start it with root:

```
Traceback (most recent call last):
  File "/home/user/.local/bin/./dymoprint_gui", line 5, in <module>
    from dymoprint.gui import main
ModuleNotFoundError: No module named 'dymoprint'
```

**Comment by maresb** [comment]
Thanks so much @EmJotGeh for the test!!!

Does it work again if you switch back to the release version with `pip install dymoprint`?

**Comment by EmJotGeh** [comment]
Hey Ben @maresb,

today i tried dymoprint again. Installed again - and all is working pretty fine with dymoprint cli and dymoprint_gui!

Thank you very much for this really excellent work :-) It was my last hardware that needed a Windows OS.

I drink a beer to you ;-)

**Comment by maresb** [comment]
That's excellent @EmJotGeh, I'm very glad!

Which version did you try? Was it the latest stable version v1.4.1? Or was it the beta release v2.0.0b0 described in #56?

There are two completely separate methods of connection in v1.4.1, and that makes development and testing difficult. But v2 has just one, so I'm eager to get that tested and merged.

**Comment by EmJotGeh** [comment]
Hey @maresb,

package dymoprint 1.4.1, installed using Python 3.11.3
- dymoprint
- dymoprint_gui

It sounds exciting that you want to simplify the connection of the dymoprinter.
