### ISSUE TITLE
Does not work on windows

### ISSUE THREAD

**Issue by Fasten90** [computerlyrik/dymoprint#51]
I got this issue when I try to use anything from dymoprint:
```C:\Users\test\dymo_print>venv\Scripts\dymoprint.exe -p mypic.jpg
Traceback (most recent call last):
  File "C:\Users\lock3\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\test\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\test\dymo_print\venv\Scripts\dymoprint.exe\__main__.py", line 5, in <module>
  File "c:\users\test\dymo_print\venv\lib\site-packages\dymoprint\command_line.py", line 34, in <module>
    from .font_config import font_filename
  File "c:\users\test\dymo_print\venv\lib\site-packages\dymoprint\font_config.py", line 9, in <module>
    from .utils import die
  File "c:\users\test\dymo_print\venv\lib\site-packages\dymoprint\utils.py", line 10, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'
```

I see at here: https://stackoverflow.com/questions/45228395/error-no-module-named-fcntl
the fcntl does not exist at Windows
And it seems right: https://docs.python.org/3/library/fcntl.html

It is planned to be working at Windows, or not?
Thank you very much your reply in advance!

And thank you your contribution in the python world :)

**Comment by maresb** [comment]
Hey, thanks for asking! Currently only Linux is supported. However I don't see any fundamental obstacle to supporting Windows. I think we would just need to refactor a few things to use PyUSB as the primary method of connecting to the device, and also to get rid of a few quirks like this `fcntl` module which you point out.

Would you be interested in submitting a PR?

**Comment by Fasten90** [comment]
Hi @maresb ,
I am so sorry for late response.
We used an another workaroud unfortunately (printing via SumatraPDF - command line). It is working at Windows.
I don't see when I can do this, so sorry I would not like to promise anything now.
If you also don't see any chance to this issue will be solved once, please feel free to close!
Thank you your contribution!
Gábor

**Comment by maresb** [comment]
Hey, no worries, thanks for asking! I'd like to leave this open if you don't mind so that I remember that Windows is a todo.
